# Generated by Django 5.0.6 on 2024-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_aboutimage_monpdf_secondpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monpdf',
            name='txtlink',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
